### ISSUE TITLE
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*'

### ISSUE THREAD

**Issue by francovp** [manuelabarca/webpay-angular#1]
Hola Manuel, 

Estaba probando tu proyecto y sale este error en la consola de la aplicación Angular y creo que proboca que la app angular nunca detecte el pago exitoso y se queda con el spinner infinitamente.

¿Tienes alguna idea de cómo se podría solucionar?

`Access to XMLHttpRequest at 'http://localhost:3410/socket.io/?EIO=3&transport=polling&t=MpZ9HB7' from origin 'http://localhost:4200' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by francovp** [comment]
Bueno, al cololar "http://localhost:4200" así:
`res.header('Access-Control-Allow-Origin', 'http://localhost:4200');`
en`app.js` del server, el error desaparece.

Ahora aparece otro error en consola 
`http://localhost:3410/socket.io/?EIO=3&transport=polling&t=MpZCRoo 404 (Not Found)`

**Comment by manuelabarca** [comment]
Eso es problema de los CORS, debes ver bien como esta declarado en el server lo de los CORS. Si lo solucionaste y podrias hacer un PR, sería de gran ayuda.
